### ISSUE TITLE
Add passwords to Piles

### ISSUE THREAD

**Issue by ralfw** [UdaraJay/Pile#26]
Let the user lock the app or a pile with a password.

Even better: Let the user lock individual entries in a pile, eg. by marking them as private or FMEO (for my eyes only).
Only if the pile has been unlocked these entries (default could be all entries) are visible/readable.

Journals can be pretty personal, even intimate places. To open up in one's journal would benefit from giving users a way to control who can see what.

**Comment by UdaraJay** [comment]
That's a good point. Thanks for the feedback!

At the moment Pile is designed as a local app that relies on the inherent security of the user's computer and operating system. I think that's a fair expectation for most users, but will leave this open for a bit to gather suggestions for future consideration.

**Comment by nathan-verghis** [comment]
Building on this (I'm writing a PR for this as we speak), I think passwords lend a neat gateway into encryption and compression of the md (the former builds on @ralfw point, the latter is more of a nice-to-have). I can make a separate Issue for this, but I think it would be important that the md files are at least encrypted, especially since it's not unlikely that a friend or family member might use my computer.
