### ISSUE TITLE
Installing from source

### ISSUE THREAD

**Issue by l0g1x** [UdaraJay/Pile#5]
## Summary

Hi, i was wondering if installing Pile from source is supported. I'm running into a roadblock because it requires a Apple Developer ID in order to complete signature creation, along with some installation error messages which i cant resolve. Am hoping to submit a PR that makes the onHover animation between different posts more snappy.

here are some commands i've ran:

<img width="1512" alt="image" src="https://github.com/UdaraJay/Pile/assets/5489842/1b258719-e58f-42a0-857a-bbb2306efb4f">
<img width="1512" alt="image" src="https://github.com/UdaraJay/Pile/assets/5489842/2e6b6698-319c-42b3-af93-a1013a34a7e5">
<img width="1512" alt="image" src="https://github.com/UdaraJay/Pile/assets/5489842/b237478a-7769-4407-a828-c2c7499114c4">

**Comment by UdaraJay** [comment]
Hey 👋 

this is because it's trying to notarize without credentials and failing– should be an easy fix if you want to just build for yourself locally. Comment out the `notarize` function call in `.erb/scripts/notarize.js` and re-running the package step. It should just leave you with un-notarized release builds in `release/build`
